# Generated by Django 4.2.3 on 2023-08-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='Market.product'),
        ),
    ]
