name: Testing
on: push


jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip install --user django
        pip install psycopg2-binary
        python3 manage.py test
